### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by sipsorcery** [pipe/sctp4j#4]
Thanks for the code.

Are there any usage examples regarding how to use `sctp4j` once the DTLS `DatagramTransport` is available?

Am I right that the `pe.pi.sctp4j.sctp.small.ThreadedAssociation` class is the main handler for processing SCTP messages received from the DTLS transport?

**Comment by steely-glint** [comment]
Thats a good question. 
I'm (slowly) working on a non-proprietary version of the |pipe| stack that would illustrate that.
I'll try and update here when I have something available.

**Comment by steely-glint** [comment]
import org.bouncycastle.tls.DTLSTransport;

public Association makeAssociation(DTLSTransport trans, AssociationListener li) {
                        a = new ThreadedAssociation(trans, li);
                        return a;
                    }

Is the best hint I can offer for now.

**Comment by sipsorcery** [comment]
Thx for the hint and thanks for the original source. We did manage to get WebRTC data channels up and running in this [project](https://github.com/sipsorcery/sipsorcery) with the help of a C# port of your work.

**Comment by steely-glint** [comment]
Could you put a link to the C# port here please, I'm sure others would find it useful.

**Comment by sipsorcery** [comment]
https://github.com/forestrf/sctp4cs
