### ISSUE TITLE
how to use this to send VideoSteam to webclient

### ISSUE THREAD

**Issue by xlb** [pipe/sctp4j#8]
Is there any example to show how to send video or anyOther message to a webclient，just like use webclient to webclient  to share their 
DesktopScreen 。

thanks！

**Comment by steely-glint** [comment]
I'm afraid not. The nearest thing is the ../whipi repo  which does send video to WHIP clients, but not data.
There is a lot of infrastructure you have to add to make a full webRTC app (mostly signalling, SDP parsers, security etc).
